stages:
  - sync

sync_to_github:
  stage: sync
  only:
    - master
  script:
    # set up user info
    - git config --global user.email "wangyiming@ihep.ac.cn"
    - git config --global user.name "dreamthreebs"

    # mirror the repo
    - git clone --mirror "$CI_REPOSITORY_URL" mirror_repo.git
    - cd mirror_repo.git

    # add github remote repo
    - git remote add github "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/dreamthreebs/psilc-mirror.git"

    # push to github
    - git push --mirror github

